### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by karmveerranawat** [thewebcrux/discord_bot#13]
Update readme.md

**Comment by mayank1784** [comment]
Kindly provide some brief on the working of bot. I will make the documnentation

**Comment by adityakaaltatva** [comment]
I will make some cool updations for documentation

**Comment by karmveerranawat** [comment]
> Kindly provide some brief on the working of bot. I will make the documnentation

Well the bot is for discord members of Webcrux community , it helps them sign up and get access to specific channels it helps create and manage community tasks and also handles the various dev pipelines

**Comment by karmveerranawat** [comment]
doc created by @adityakaaltatva .
closing issue , readme can be updated as required.

**Comment by karmveerranawat** [comment]
doc created by @adityakaaltatva 
closing issue , readme can be updated as required.
